# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# This file contains a template configuration file, which is typically
# placed as .hlint.yaml in the root of your project


# Warnings currently triggered by your code
- ignore: {name: "Unused LANGUAGE pragma"}
- ignore: {name: "Use module export list"}
- ignore: {name: "Redundant do"}
- ignore: {name: "Eta reduce"}
- ignore: {name: "Redundant bracket"}
- ignore: {name: "Redundant $"}
- ignore: {name: "Reduce duplication"}
- ignore: {name: "Use camelCase"}
- ignore: {name: "Use pure"}

# This package doesn't depend on extra
- ignore: {name: "Use lower"}
- ignore: {name: "Use upper"}
- ignore: {name: "Use drop1"}
- ignore: {name: "Use lastDef"}
- ignore: {name: "Use zipFrom"}
